server:
  port: 8097
  address: 0.0.0.0

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/schoolSystem
    username: root
    password: asdQWE123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: 'org.hibernate.dialect.MySQL5InnoDBDialect'

  liquibase:
    change-log: classpath:db.changelog/production.sql

#classpath:liquibase/changes/prod.sql
